#!/bin/bash

make all || exit
./main > a.data || exit
make test.schema.txt || exit
luajit foo.lua c.data || exit
xxd -g 1 a.data || exit
echo
xxd -g 1 c.data || exit
diff a.data c.data
lunit.sh -i `which luajit` test/sanity.lua
